### ISSUE TITLE
Making the tiles clickable

### ISSUE THREAD

**Issue by henryla92** [fdoyle/flutter_demo_movies#1]
Hi,
Do you know how to make the tiles clickable? The Positioned.fill after the stack is blocking the GestureDetectors on the cards themselves. 

I tried a bunch of things but can't seem to get it working. 

Thanks!

**Comment by fdoyle** [comment]
Yeah, I've been thinking about this, it is indeed a pretty significant flaw to this method. 

I think the "right" solution would be to convert my awful pageview "gesturedetector" into a "real" gesturedetector that provides similar events.

**Comment by henryla92** [comment]
Could you please help me find a solution?

I really like the animation but my knowledge of flutter is limited, I can't really find a fix for it. 

Thanks!

**Comment by akshaybengani** [comment]
> Yeah, I've been thinking about this, it is indeed a pretty significant flaw to this method.
> 
> I think the "right" solution would be to convert my awful pageview "gesturedetector" into a "real" gesturedetector that provides similar events.

I am also encountering very same problem, I am unable to add any Gesture Detector on my card, could you please add that up in posters code.
Thankyou

**Comment by osama383** [comment]
> Yeah, I've been thinking about this, it is indeed a pretty significant flaw to this method.
> I think the "right" solution would be to convert my awful pageview "gesturedetector" into a "real" gesturedetector that provides similar events.


wrapping the pageview.builder with a gesture detector worked for me

**Comment by akshaybengani** [comment]
> > Yeah, I've been thinking about this, it is indeed a pretty significant flaw to this method.
> > I think the "right" solution would be to convert my awful pageview "gesturedetector" into a "real" gesturedetector that provides similar events.
> 
> wrapping the pageview.builder with a gesture detector worked for me

Can you please share the code snippet for the same

**Comment by osama383** [comment]
`Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Stack(children: <Widget>[
            PosterScrollWidget(courses, currentPage),
            Positioned.fill(
              child: GestureDetector(
                onTap: () {
                  print(' index of tile clicked: ${currentPage.round()}');
                },
                child: PageView.builder(
                    `

**Comment by osama383** [comment]
please let me know if something is not clear

**Comment by kipgparker** [comment]
Yeah, that code does work, it doesn't seem like the best way to do it. is there a way you can use a more accurately shaped for the tiles, or even if you could add the gesture detector to the tiles?

Are there any similar implementations that do this this well?

**Comment by charlotzzz** [comment]
> please let me know if something is not clear

Hi, your code is great but it seems to only work for gestures on a card as a whole. For me, my cards are filled with another widget that has build-in on-tap gestures. Thus, wrapping the position.builder does not allow these gestures. Do you think there is any other way of doing this?

**Comment by syedosama94** [comment]
Can you share your code?

**Comment by osama383** [comment]
> > please let me know if something is not clear
> 
> Hi, your code is great but it seems to only work for gestures on a card as a whole. For me, my cards are filled with another widget that has build-in on-tap gestures. Thus, wrapping the position.builder does not allow these gestures. Do you think there is any other way of doing this?

Can you share your code?

**Comment by charlotzzz** [comment]
> > > please let me know if something is not clear
> > 
> > 
> > Hi, your code is great but it seems to only work for gestures on a card as a whole. For me, my cards are filled with another widget that has build-in on-tap gestures. Thus, wrapping the position.builder does not allow these gestures. Do you think there is any other way of doing this?
> 
> Can you share your code?

Absolutely, here it is.

I used this `List dataList` in the place of the image list in the original code. 

`void cardGenerator() {
    dataList = new List(4);
    dataList[0] = CardItem(listData: topic2);
    dataList[1] = CardItem(listData: topic1);
    dataList[2] = CardItem(listData: topic2);
    dataList[3] = CardItem(listData: topic1);
  }`

My custom class `CardItem()` is basically a card that shows a list of clickable items that will open a web view. Within the `CardItem()`, there is another custom class `ListItems()` where I put these clickable items.

`void articleGenerator() {
    var size = articleData.length;
    articleList = new List<Widget>(size);

    for (var i = size - 1; i >= 0; i--) {
      var title = articleData[i][3];
      var author = articleData[i][4];
      var source = articleData[i][5];
      var url = articleData[i][6];
      // var description = articleData[i][8];

      articleList[i] = FractionallySizedBox(
        child: Column(children: <Widget>[
          FractionallySizedBox(
            widthFactor: 1,
            child: Container(
              decoration: BoxDecoration(
                gradient: LinearGradient(colors: [
                  Color.fromRGBO(0, 0, 0, 0.5),
                  Color.fromRGBO(0, 0, 0, 0.3)
                ], begin: Alignment.topCenter, end: Alignment.bottomCenter),
              ),
              // color: Color.fromRGBO(0, 0, 0, 0.4),
              child: FlatButton(
                onPressed: () {
                  webViewLauncher(url, title);
                  print(url);
                },
                child: SizedBox(
                  height: 93,
                  child: Padding(
                    padding: const EdgeInsets.all(12),
                    child: Container(
                      alignment: Alignment.topLeft,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisAlignment: MainAxisAlignment.start,
                        children: <Widget>[
                          Text('$title',
                              maxLines: 2,
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                              )),
                          Text(
                            '$author | $source',
                            style: TextStyle(
                              color: Colors.white,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ]),
      );
    }
  }`

The issue is that the `onPress()` in `ListItems()` is overlaid by the `Positioned.fill()` so that the tap gesture is no longer detected.

**Comment by osama383** [comment]
> > > > please let me know if something is not clear
> > > 
> > > 
> > > Hi, your code is great but it seems to only work for gestures on a card as a whole. For me, my cards are filled with another widget that has build-in on-tap gestures. Thus, wrapping the position.builder does not allow these gestures. Do you think there is any other way of doing this?
> > 
> > 
> > Can you share your code?
> 
> Absolutely, here it is.
> 
> I used this `List dataList` in the place of the image list in the original code.
> 
> `void cardGenerator() { dataList = new List(4); dataList[0] = CardItem(listData: topic2); dataList[1] = CardItem(listData: topic1); dataList[2] = CardItem(listData: topic2); dataList[3] = CardItem(listData: topic1); }`
> 
> My custom class `CardItem()` is basically a card that shows a list of clickable items that will open a web view. Within the `CardItem()`, there is another custom class `ListItems()` where I put these clickable items.
> 
> `void articleGenerator() {
> var size = articleData.length;
> articleList = new List(size);
> 
> ```
> for (var i = size - 1; i >= 0; i--) {
>   var title = articleData[i][3];
>   var author = articleData[i][4];
>   var source = articleData[i][5];
>   var url = articleData[i][6];
>   // var description = articleData[i][8];
> 
>   articleList[i] = FractionallySizedBox(
>     child: Column(children: <Widget>[
>       FractionallySizedBox(
>         widthFactor: 1,
>         child: Container(
>           decoration: BoxDecoration(
>             gradient: LinearGradient(colors: [
>               Color.fromRGBO(0, 0, 0, 0.5),
>               Color.fromRGBO(0, 0, 0, 0.3)
>             ], begin: Alignment.topCenter, end: Alignment.bottomCenter),
>           ),
>           // color: Color.fromRGBO(0, 0, 0, 0.4),
>           child: FlatButton(
>             onPressed: () {
>               webViewLauncher(url, title);
>               print(url);
>             },
>             child: SizedBox(
>               height: 93,
>               child: Padding(
>                 padding: const EdgeInsets.all(12),
>                 child: Container(
>                   alignment: Alignment.topLeft,
>                   child: Column(
>                     crossAxisAlignment: CrossAxisAlignment.start,
>                     mainAxisAlignment: MainAxisAlignment.start,
>                     children: <Widget>[
>                       Text('$title',
>                           maxLines: 2,
>                           textAlign: TextAlign.left,
>                           style: TextStyle(
>                             color: Colors.white,
>                             fontSize: 16,
>                             fontWeight: FontWeight.bold,
>                           )),
>                       Text(
>                         '$author | $source',
>                         style: TextStyle(
>                           color: Colors.white,
>                         ),
>                       ),
>                     ],
>                   ),
>                 ),
>               ),
>             ),
>           ),
>         ),
>       ),
>     ]),
>   );
> }
> ```
> 
> }`
> 
> The issue is that the `onPress()` in `ListItems()` is overlaid by the `Positioned.fill()` so that the tap gesture is no longer detected.

Hi. So I am unable to find a solution to your problem. I'll let you know if and when I am able to find a workaround. If you solve it, please share the solution. Thanks

**Comment by charlotzzz** [comment]
> > > > > please let me know if something is not clear
> > > > 
> > > > 
> > > > Hi, your code is great but it seems to only work for gestures on a card as a whole. For me, my cards are filled with another widget that has build-in on-tap gestures. Thus, wrapping the position.builder does not allow these gestures. Do you think there is any other way of doing this?
> > > 
> > > 
> > > Can you share your code?
> > 
> > 
> > Absolutely, here it is.
> > I used this `List dataList` in the place of the image list in the original code.
> > `void cardGenerator() { dataList = new List(4); dataList[0] = CardItem(listData: topic2); dataList[1] = CardItem(listData: topic1); dataList[2] = CardItem(listData: topic2); dataList[3] = CardItem(listData: topic1); }`
> > My custom class `CardItem()` is basically a card that shows a list of clickable items that will open a web view. Within the `CardItem()`, there is another custom class `ListItems()` where I put these clickable items.
> > `void articleGenerator() {
> > var size = articleData.length;
> > articleList = new List(size);
> > ```
> > for (var i = size - 1; i >= 0; i--) {
> >   var title = articleData[i][3];
> >   var author = articleData[i][4];
> >   var source = articleData[i][5];
> >   var url = articleData[i][6];
> >   // var description = articleData[i][8];
> > 
> >   articleList[i] = FractionallySizedBox(
> >     child: Column(children: <Widget>[
> >       FractionallySizedBox(
> >         widthFactor: 1,
> >         child: Container(
> >           decoration: BoxDecoration(
> >             gradient: LinearGradient(colors: [
> >               Color.fromRGBO(0, 0, 0, 0.5),
> >               Color.fromRGBO(0, 0, 0, 0.3)
> >             ], begin: Alignment.topCenter, end: Alignment.bottomCenter),
> >           ),
> >           // color: Color.fromRGBO(0, 0, 0, 0.4),
> >           child: FlatButton(
> >             onPressed: () {
> >               webViewLauncher(url, title);
> >               print(url);
> >             },
> >             child: SizedBox(
> >               height: 93,
> >               child: Padding(
> >                 padding: const EdgeInsets.all(12),
> >                 child: Container(
> >                   alignment: Alignment.topLeft,
> >                   child: Column(
> >                     crossAxisAlignment: CrossAxisAlignment.start,
> >                     mainAxisAlignment: MainAxisAlignment.start,
> >                     children: <Widget>[
> >                       Text('$title',
> >                           maxLines: 2,
> >                           textAlign: TextAlign.left,
> >                           style: TextStyle(
> >                             color: Colors.white,
> >                             fontSize: 16,
> >                             fontWeight: FontWeight.bold,
> >                           )),
> >                       Text(
> >                         '$author | $source',
> >                         style: TextStyle(
> >                           color: Colors.white,
> >                         ),
> >                       ),
> >                     ],
> >                   ),
> >                 ),
> >               ),
> >             ),
> >           ),
> >         ),
> >       ),
> >     ]),
> >   );
> > }
> > ```
> > 
> > 
> > }`
> > The issue is that the `onPress()` in `ListItems()` is overlaid by the `Positioned.fill()` so that the tap gesture is no longer detected.
> 
> Hi. So I am unable to find a solution to your problem. I'll let you know if and when I am able to find a workaround. If you solve it, please share the solution. Thanks

Yeah, thanks!

**Comment by fdoyle** [comment]
I've made some changes to fix this issue. 

Now, at the bottom of main, you'll see a PagerGestureDetector. Now, instead of having a ViewPager sitting overtop your content, your content is now a child of PagerGestureDetector, which allows child GestureDetectors to work as expected, without any weirdness. 

I've also added a tap detector that shows the url to demonstrate that functionality. 

Note, this is a fairly naive implementation, there are likely optimizations you could make so that you don't have to rebuild the entire child tree, but since it's an example, I wanted to make as few opinions as possible about how the components could be used.

**Comment by fdoyle** [comment]
If there are still issues, please feel free to open a new issues or continue commenting here, but I believe this is resolved.
