### ISSUE TITLE
How to change hidden card top to bottom?

### ISSUE THREAD

**Issue by bhanuka96** [fdoyle/flutter_demo_movies#2]
1. Is it possible to change vertical and hidden card change into the top to bottom? 

2. how to show multiple main cards?(by default 1 main hard and 2 hidden cards, can change 2 main cards and 1 hidden card)

3. can show to hidden card both left and right(top and bottom)?

**Comment by fdoyle** [comment]
1 and 2 are definitely both possible, just use different math. X, Y, and scale are all just functions of page. You can do whatever you want with them. 

The third one should be possible as well, but you'd have to make some significant changes to how z ordering is handled. Right now, the "top" card is always the "top" card, that never changes, it just slides off-screen. If you wanted to slide it back under other cards, you'd have to do something clever.
