### ISSUE TITLE
How to make the initial image the one on the very top?

### ISSUE THREAD

**Issue by charlotzzz** [fdoyle/flutter_demo_movies#3]
Hi, I found that, after building, the initial image is the last one in the stack, meaning that users have to swipe from the last image to the one on the top. Is there any way to make the initial image the one on the very top?

**Comment by fdoyle** [comment]
Sure, just reverse the list before you pass it in, or read the list backwards.

**Comment by charlotzzz** [comment]
> Sure, just reverse the list before you pass it in, or read the list backwards.

Thanks, I actually meant that the initial screen looks like this on my emulator:
<img width="356" alt="Screen Shot 2020-05-27 at 4 27 13 PM" src="https://user-images.githubusercontent.com/63896238/83082004-f9550c00-a036-11ea-8ee5-beed8e6ccb71.png">

But I kinda want the initial screen to look like this:
<img width="356" alt="Screen Shot 2020-05-27 at 4 27 23 PM" src="https://user-images.githubusercontent.com/63896238/83082011-040fa100-a037-11ea-87dc-1209022fe506.png">

**Comment by fdoyle** [comment]
Ah, I understand. 

I've recently updated the code, so take a look at that. 

With the new logic, you should be able to just set a different initial value to Page, and it'll work.

**Comment by charlotzzz** [comment]
> Ah, I understand.
> 
> I've recently updated the code, so take a look at that.
> 
> With the new logic, you should be able to just set a different initial value to Page, and it'll work.

Thanks!!
